apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste2
  name: teste2
spec:
  containers:
  - image: nginx
    name: teste2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
